### ISSUE TITLE
Public key deprecated in Plaid

### ISSUE THREAD

**Issue by dand-oss** [ebridges/plaid2qif#20]
https://plaid.com/docs/link/#introduction-to-link
When you collect you secret key, there is this information:
A note on Plaid keys
All implementations of Plaid created after July 23, 2020 will use a link_token instead of a public_key. To learn more, view our docs.

How to use link_token instead of public_key?

**Comment by ebridges** [comment]
This is potentially fixed via https://github.com/ebridges/plaid2qif/pull/21

**Comment by bhipple** [comment]
Unfortunately no, I think this is a different issue: you and I have grandfathered in `public_key`s, so we can still use plaid2qif, but new users can't create a `public_key` so they need documentation and/or software support to use a `link_token` for the one-time Plaid auth setup.   This probably isn't hard to support, but since it's working for me already I'm a little nervous about tearing up my setup ...

**Comment by ryevdokimov** [comment]
Is it possible to get this work with just a link_token? As @bhipple mentioned above, there is no documentation on this.

**Comment by ebridges** [comment]
I've made some changes to address this.  You can see the current state in PR #28 

This is working for me locally, but would like to get some other eyes on it to be sure.

@ryevdokimov / @bhipple / @dand-oss ?
