### ISSUE TITLE
Add error messages?

### ISSUE THREAD

**Issue by jcrben** [ebridges/plaid2qif#5]
I ran this properly at first, but when I came back to it I accidentally misspelled account as account. It took me a while to figure it out.

Docopt has `raise DocoptExit()` at the end but it doesn't pass a generic message. In their docs they point to a way to use python-schema for validation https://github.com/docopt/docopt#data-validation.

**Comment by ebridges** [comment]
Hi thank you for opening an issue and expressing ideas for how to improve this.  Would you share or otherwise describe the error message you got for this?  Implementing validation for this project would be a chunk of work, and want to be sure I'm addressing the issue you saw.

If, as you say, you misspelled one of the `account` args, I'd like to think that it would have just thrown a key error here [plaid2qif.py#L158](https://github.com/ebridges/plaid2qif/blob/master/plaid2qif/plaid2qif.py#L158)?  If that's all it is, I think I have some other ideas how to handle it.

**Comment by jcrben** [comment]
Sorry, that should have been misspelled account as acount. I think there was no error at all.

**Comment by ebridges** [comment]
Thanks, please feel free to follow up if you have any other concerns.
